# vint: 
#   config_path: "../../train/config/vint.yaml"
#   ckpt_path: "../model_weights/vint.pth"

# late_fusion: 
#   config_path: "../../train/config/late_fusion.yaml"
#   ckpt_path: "../model_weights/vint_late_fusion.pth"

# gnm: 
#   config_path: "../../train/config/gnm.yaml"
#   ckpt_path: "../model_weights/gnm_large.pth"

nomad: 
  config_path: "../../train/config/nomad.yaml"
  ckpt_path: "../../deployment/model_weights/nomad.pth"
  
nomad_adapter:  # nomad_adapterの設定を追加
  config_path: "../../train/config/nomad_adapter.yaml"
  ckpt_path: "../../deployment/model_weights/nomad.pth"  # ベースモデルのパス
  adapter_path:
    task1: "/ssd/source/navigation/visualnav-transformer/train/experiments/nomad_adapter/nomad_adapter_exe/adapter_dp_casa_49.pth"
    # task1: "/ssd/source/navigation/visualnav-transformer/train/experiments/nomad_adapter/nomad_adapter_exe/adapter_dp_19.pth"