# vint: 
#   config_path: "../../train/config/vint.yaml"
#   ckpt_path: "../model_weights/vint.pth"

# late_fusion: 
#   config_path: "../../train/config/late_fusion.yaml"
#   ckpt_path: "../model_weights/vint_late_fusion.pth"

# gnm: 
#   config_path: "../../train/config/gnm.yaml"
#   ckpt_path: "../model_weights/gnm_large.pth"

nomad: 
  config_path: "../../train/config/nomad.yaml"
  ckpt_path: "../../deployment/model_weights/nomad.pth"
  adapter_path:
    task1: "/ssd/source/navigation/visualnav-transformer/train/experiments/nomad_adapter/nomad_adapter_exe/adapter_29_20241103_231907.pth"
    # task2: "/ssd/source/navigation/visualnav-transformer/train/experiments/nomad_adapter/nomad_adapter_exe/adapter_epoch_timestamp.pth"
    # task3: "/ssd/source/navigation/visualnav-transformer/train/experiments/nomad_adapter/nomad_adapter_exe/adapter_epoch_timestamp.pth" 
  


# add your own model configs here after saving the *.pth file to ../model_weight