twist_mux:
  topics:
    - name: nomad_vels
      topic: /cmd_vel_mux/input/navi
      timeout: 0.3
      priority: 100
      short_desc: "The default cmd_vel, controllers unaware that we are multiplexing cmd_vel should come here"
    
    - name: teleop
      topic: /cmd_vel_mux/input/teleop
      timeout: 0.5
      priority: 30
      short_desc: "Teleoperation velocity commands"
      
    - name: gnm_recovery
      topic: /cmd_vel_mux/input/recovery
      timeout: 0.1
      priority: 50
      short_desc: "Recovery behaviors velocity commands"
      
  output: /cmd_vel_mux/output/ohana
