datasets:
  twist_data:
    data_folder: /ssd/source/navigation/asset/nomad_adapter_dataset/raw_data_4.0hz
    train: /ssd/source/navigation/asset/nomad_adapter_dataset/raw_data_4.0hz
    test: /ssd/source/navigation/asset/nomad_adapter_dataset/raw_data_4.0hz 