defaults:
  - nomad_adapter

# データセット設定の更新
datasets:
  twist_data:
    data_folder: /ssd/source/navigation/visualnav-transformer/train/vint_train/data/nomad_adapter_dataset/raw_data
    train: /ssd/source/navigation/visualnav-transformer/train/vint_train/data/nomad_adapter_dataset/data_splits/twist_data/train/
    test: /ssd/source/navigation/visualnav-transformer/train/vint_train/data/nomad_adapter_dataset/data_splits/twist_data/test/

# Twist出力用のパラメータ
action:
  linear_scale: 1.0  # 線形速度のスケール
  angular_scale: 1.0  # 角速度のスケール 