defaults:
  - nomad_adapter

# データセット設定の更新
datasets:
  twist_data:
    data_folder: /ssd/source/navigation/asset/nomad_adapter_dataset/raw_data/raw_data4.0hz
    train: /ssd/source/navigation/asset/nomad_adapter_dataset/raw_data4.0hz/processed_data
    # test: /ssd/source/navigation/visualnav-transformer/train/vint_train/data/nomad_adapter_dataset/data_splits/twist_data/test/
    goals_per_obs: 1
    negative_mining: False
    
# Twist出力用のパラメータ
action:
  linear_scale: 1.0  # 線形速度のスケール
  angular_scale: 1.0  # 角速度のスケール 

# モデル設定
model_type: nomad_adapter
adapter_bottleneck_dim: 64  # Adapterのボトルネック次元
load_run: nomad/pretrained  # ベースとなる事前学習済みNoMaDモデル

# 学習設定
train_params:
  batch_size: 32
  num_workers: 4
  lr: 1e-4
  num_epochs: 100
  save_freq: 10
  eval_freq: 5

project_name: nomad_adapter_twist
run_name: twist_adapter_test